[project]
name = "smart-building-digital-twin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BaptVic78", email = "victor.rouleau@edu.ece.fr" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
smart-building-digital-twin = "smart_building_digital_twin:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
